### ISSUE TITLE
kapi tests

### ISSUE THREAD

**Issue by gbellidoprieto** [GeoOcean/BlueMath_tk#34]
- [kma.py]: En el ejemplo indicas 'kma_centroids' como el 'nearest centroid index'. Creo que esto equivale a las "Best Machine Units- BMUS", que he obtenido con la misma función 'bmus = kma.fit_predict(partition_df)'.

**Comment by lauracagigal** [comment]
allow seed in KMA to be None: [here](https://github.com/GeoOcean/BlueMath_tk/blob/main/bluemath_tk/datamining/kma.py#L132)
@gbellidoprieto
