### ISSUE TITLE
Add a Matrix Strategy to GitHub Actions for Testing BlueMath on Multiple OS and Python Versions

### ISSUE THREAD

**Issue by fernanqv** [GeoOcean/BlueMath_tk#39]
To verify that BlueMath works on multiple Python versions across different operating systems, a matrix with various OS and Python versions should be added to the GitHub Actions workflow python-tests.yml

Something similar to what is explained in this link:  
https://www.geeksforgeeks.org/the-matrix-strategy-in-github-actions/

**Comment by tausiaj** [comment]
Closed issue in #42
